[project]
name = "sync-remote-control"
version = "0.1.0"
authors = [
  { name = "Your Name", email = "your.email@example.com" }
]
description = "局域网批量远程控制与操作同步工具"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/sync-remote-control"
"Bug Tracker" = "https://github.com/yourusername/sync-remote-control/issues"
